name: MLOps CI

on:
  push:
    branches:
    - main
  pull-request:
    branches:
      - main
jobs:
    workflow:
      name: Build and Test
      runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Repository
        users: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # python --version
          python-version: '3.11.13'
          cache: 'pip'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # MLOps Specific steps
      - name: Data Validation
        run: |
          python src/data/run_processing.py --output_file data/processed/cleaned_house_data2.csv --input_file data/raw/house_data.csv

          
        


